import type { Metadata } from 'next'

import { ReactNode } from 'react'

import Link from 'next/link'

import '@/styles/index.scss'

import styles from './layout.module.scss'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang={'en'}>
      <body>
        <header className={styles.header}>
          <Link href={'/signUp'}>signUp</Link>
          <br />
          <Link href={'/signIn'}>signIn</Link>
          <br />
          <Link href={'/profile'}>profile</Link>
        </header>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  )
}
