import type { Metadata } from 'next'

import { ReactNode } from 'react'

import { Providers } from '@/app/providers'
import { AppSideBar } from '@/common/components/AppSidebar'
import { Header } from '@/common/components/Header/Header'
import { Theme } from '@radix-ui/themes'
import NextTopLoader from 'nextjs-toploader'

import '@/styles/index.scss'

import styles from './layout.module.scss'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'INC-Project',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang={'en'}>
      <body>
        <NextTopLoader color={'#397df6'} showSpinner={false} />
        <Providers>
          <Theme className={styles.bodyContainer} style={{ backgroundColor: 'transparent' }}>
            <Header />
            <AppSideBar />
            <main className={styles.main}>{children}</main>
          </Theme>
        </Providers>
      </body>
    </html>
  )
}
