import type { Metadata } from 'next'

import { ReactNode } from 'react'

import { Auth } from '@/common/components/AuthContainer/Auth'
import { Header } from '@/common/components/Header/Header'
import { Theme } from '@radix-ui/themes'

import '@/styles/index.scss'

import styles from './layout.module.scss'

import { Providers } from './providers'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang={'en'}>
      <body>
        <Providers>
          <Theme className={styles.bodyContainer} style={{ backgroundColor: 'transparent' }}>
            <Header />
            <main className={styles.main}>
              <Auth>{children}</Auth>
            </main>
          </Theme>
        </Providers>
      </body>
    </html>
  )
}
